language: android
android: 
 components:
   - build-tools-26.0.2
   - android-26
   - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

